apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: grafana-admin-password
spec:
  length: 32
  digits: 6
  symbols: 4
  symbolCharacters: "-_@$"
  noUpper: false
  allowRepeat: false
