apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: "8.10.4"
      helm:
        valueFiles:
          - $values/components/grafana/base/values.yaml
          - $values/envs/iks/nonprod/grafana/values.yaml
    - repoURL: https://github.com/thomas-mattsson/interact-gateway.git
      ref: values
    - repoURL: https://github.com/thomas-mattsson/interact-gateway.git
      path: ./components/grafana/base
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
