apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: lokistack
  namespace: monitoring
spec:
  size: 1x.extra-small
  storage:
    schemas:
      - version: v13
        effectiveDate: "2024-01-01"
    secret:
      # Created by the lokistack-secret-bootstrap Job (see secret-bootstrap-job.yaml)
      # which reads the OBC Secret+ConfigMap and assembles the required fields.
      name: lokistack-storage-secret
      type: s3
    tls:
      # NooBaa S3 endpoint cert is signed by the OpenShift service-serving-signer CA,
      # which is injected into the openshift-service-ca.crt ConfigMap in every namespace.
      caName: openshift-service-ca.crt
      caKey: service-ca.crt
  storageClassName: ocs-storagecluster-ceph-rbd
  tenants:
    mode: openshift-logging
