apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: lokistack-obc
  namespace: monitoring
spec:
  storageClassName: openshift-storage.noobaa.io
  generateBucketName: lokistack
