apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: loki-obc-store
  namespace: monitoring
spec:
  provider:
    kubernetes:
      remoteNamespace: monitoring
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        token:
          bearerToken:
            name: loki-obc-reader-token
            key: token
