apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apic-operator
  namespace: argocd
  labels:
    group: applications
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: idig
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/apic/operator
  ignoreDifferences:
    # OCP Pipelines operator and OCP itself stamp labels onto every namespace
    - kind: Namespace
      jsonPointers:
        - /metadata/labels/openshift-pipelines.tekton.dev~1namespace-reconcile-version
        - /metadata/labels/openshift-pipelines.tekton.dev~1namespace-trusted-configmaps-version
        - /metadata/labels/pod-security.kubernetes.io~1audit
        - /metadata/labels/pod-security.kubernetes.io~1audit-version
        - /metadata/labels/pod-security.kubernetes.io~1warn
        - /metadata/labels/pod-security.kubernetes.io~1warn-version
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: false
      selfHeal: true