apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nanogw-operator
  namespace: argocd
  labels:
    group: applications
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: idig
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/nanogw/operator
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true