apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  hosts.override: |
    hosts {
        REPLACE_ME_ENVOY_IP ai.REPLACE_ME_ENDPOINT_DOMAIN
        REPLACE_ME_ENVOY_IP idig.REPLACE_ME_ENDPOINT_DOMAIN
        fallthrough
    }
