apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret/password.yaml
  - secret/external-secret.yaml
  - tls-service-account.yaml
  - tls-secret-store.yaml
  - tls-external-secret.yaml
