apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-tls-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: grafana-tls-store
    kind: ClusterSecretStore
  target:
    name: grafana-tls-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: CLUSTER_TLS_SECRET_NAME   # patched per env
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: CLUSTER_TLS_SECRET_NAME   # patched per env
        property: tls.key
