apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-tls-sa
  namespace: grafana
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-tls-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-tls-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-tls-secret-reader
subjects:
  - kind: ServiceAccount
    name: grafana-tls-sa
    namespace: grafana
