apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: grafana-tls-store
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      auth:
        serviceAccount:
          name: grafana-tls-sa
          namespace: grafana
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: grafana
