apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: analytics-cluster-patch.yaml
    target:
      group: analytics.apiconnect.ibm.com
      version: v1beta1
      kind: AnalyticsCluster
      name: idig-analytics
      namespace: idig

  - path: devportal-cluster-patch.yaml
    target:
      group: devportal.apiconnect.ibm.com
      version: v1beta1
      kind: DevPortalCluster
      name: idig-devportal
      namespace: idig

  - path: nanogw-cluster-patch.yaml
    target:
      group: nanogateway.apiconnect.ibm.com
      version: v1beta1
      kind: NanoGatewayCluster
      name: idig-nanogw
      namespace: idig
