apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy-ocp
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: envs/odf/nonprod/alloy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
