apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-tls-es
spec:
  data:
    - secretKey: tls.crt
      remoteRef:
        key: idig-install-cluster-e7d3d93b8b317d269525bf063b24f98d-0000
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: idig-install-cluster-e7d3d93b8b317d269525bf063b24f98d-0000
        property: tls.key
