ingress:
  enabled: true
  ingressClassName: public-iks-k8s-nginx
  hosts: []
  # To use the cluster TLS certificate, uncomment and set the values below.
  # See README.md for full instructions.
  # hosts:
  #   - grafana.<cluster-id>.<region>.containers.appdomain.cloud
  # tls:
  #   - secretName: grafana-tls-secret
  #     hosts:
  #       - grafana.<cluster-id>.<region>.containers.appdomain.cloud

persistence:
  storageClassName: ibmc-vpc-block-10iops-tier
