ingress:
  enabled: true
  ingressClassName: public-iks-k8s-nginx
  # hosts: []
  # To use the cluster TLS certificate, uncomment and set the values below.
  # See README.md for full instructions.
  hosts:
    - grafana.idig-install-cluster-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
  tls:
    - secretName: grafana-tls-secret
      hosts:
        - grafana.idig-install-cluster-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud

persistence:
  storageClassName: ibmc-vpc-block-10iops-tier
